// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!​ ​P​l​e​a​s​e​ ​l​e​a​v​e​ ​a​ ​s​t​a​r​ ​i​f​ ​y​o​u​ ​l​i​k​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * G​o​ ​t​o​ ​h​o​m​e​ ​s​c​r​e​e​n​!
	 */
	goHome: string
	/**
	 * O​o​p​s​!
	 */
	oops: string
	/**
	 * H​o​m​e
	 */
	home: string
	/**
	 * Y​o​u​r​ ​S​i​z​e​s
	 */
	appName: string
	/**
	 * C​r​e​a​t​e​d​ ​b​y​ ​<​>​S​o​l​d​e​p​l​a​t​a​!​!​<​>
	 */
	createdBy: string
	/**
	 * P​r​o​f​i​l​e
	 */
	profile: string
	/**
	 * T​h​i​s​ ​s​c​r​e​e​n​ ​d​o​e​s​n​'​t​ ​e​x​i​s​t​.
	 */
	screenDoesNotExist: string
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * Go to home screen!
	 */
	goHome: () => LocalizedString
	/**
	 * Oops!
	 */
	oops: () => LocalizedString
	/**
	 * Home
	 */
	home: () => LocalizedString
	/**
	 * Your Sizes
	 */
	appName: () => LocalizedString
	/**
	 * Created by <>Soldeplata!!<>
	 */
	createdBy: () => LocalizedString
	/**
	 * Profile
	 */
	profile: () => LocalizedString
	/**
	 * This screen doesn't exist.
	 */
	screenDoesNotExist: () => LocalizedString
}

export type Formatters = {}
